REGULAR_DICT = {
    "m": "м",
    "e": "е",
    '̩': "",
    "l": "л",
    'ɪ': "и",
    "s": "с",
    "f": "ф",
    "n": "н",
    "t": "т",
    "i": "и",
    "p": "п",
    "k": "к",
    "ɔ": "о",
    "o": "о",
    "ɑ": "о",
    "d": "д",
    "ɡ": "г",
    "ɛ": "е",
    "z": "з",
    "ŋ": "нг",
    "v": "в",
    "b": "б",
    'ʌ': "а",
    'ʤ': "дж",
    'ʒ': "дж",
    'u': "у",
    "ʃ":"ш",
    'æ': "е",
    'j':"й",
    "ə":"е",
    "w":"у",
    "h":"х",
    "ʧ":"ч",
    'a':"а",
    'ʊ':"ю",
    "θ":'с',
    'ɹ': "р",
    'r': "р",
    'ð':"з",
    'g': 'г',
}


VOWEL_EXTRA_DICT = {
    "o":"о",
    "a":"а",
    "e": "е",
}

KNOWN_WORDS = {
    "disney": "дисней",
    "auchan": "ашан",
    "facepalm": "фейспалм",
    "cringe": "кринж",
    "mars": "марс",
    "rexona": "рексона",
    "coca-cola": "кока-кола",
    "jacobs": "якобс",
    "schweppes": "швепс",
    "pulpy": "палпи",
    "orbit": "орбит",
    "nescafe": "нескафе",
    "jardin": "жардин",
    "nesquik": "несквик",
    "fruittella": "фрутелла",
    "actimel": "актимель",
    "snickers": "сникерс",
    "l'oreal": "лореаль",
    "l oreal": "лореаль", 
    "oreal": "лореаль",
    "paris": "париж",
    "nivea": "нивея", 
    "garnier": "гарньер", 
    "vici": "вичи", 
    "natura siberica": "натура сиберика", 
    "colgate": "колгейт", 
    "gillette": "джилет", 
    "heinz": "хайнц", 
    "dove": "дав", 
    "syoss": "сйосс", 
    "color": "колор", 
    "premium": "премиум", 
    "gold": "голд", 
    "fresh": "фреш", 
    "extra": "экстра", 
    "classic": "классик", 
    "ultra": "ультра", 
    "baby": "бейби", 
    "original": "ориджинал", 
    "white": "уайт", 
    "care": "кер", 
    "librederm": "либредерм", 
    "organic": "органик", 
    "green": "грин", 
    "days": "дейз", 
    "black": "блэк", 
    "pampers": "памперс", 
    "perfect": "перфект", 
    "sensitive": "сенситив", 
    "lipton": "липтон", 
    "nestle": "нестле", 
    "plus": "плюс", 
    "palmolive": "палмолив", 
    "valio": "валио", 
    "kids": "кидс", 
    "professional": "профессионал", 
    "power": "пауэр", 
    "maybelline": "мэйбеллин", 
    "expert": "эксперт", 
    "purina": "пурина", 
    "pantene": "пантин", 
    "clean": "клин", 
    "huggies": "хаггис", 
    "york": "йорк", 
    "soft": "софт", 
    "pure": "пье", 
    "palette": "палет", 
    "normal": "нормал", 
    "always": "олвейз", 
    "president": "президент", 
    "naturals": "натурал", 
    "whiskas": "вискас", 
    "active": "актив", 
    "danone": "данон", 
    "chateau": "шато", 
    "splat": "сплат", 
    "grand": "гранд", 
    "sport": "спорт", 
    "head": "хед", 
    "head & shoulders": "хед энд шолдерс",
    "head and shoulders": "хед энд шолдерс",
    "head&shoulders": "хед энд шолдерс",
    "h & s": "хед энд шолдерс",
    "h&s": "хед энд шолдерс",
    "gliss kur": "глисс кур",
    "schwarzkopf": "шварцкопф", 
    "maggi": "магги", 
    "bonduelle": "бондюэль", 
    "sauvignon": "совиньон", 
    "blanc": "блан", 
    "lenor": "ленор", 
    "kotanyi": "котани", 
    "bella": "белла", 
    "petit": "пети", 
    "cream": "крем", 
    "maxi": "макси", 
    "ariel": "ариэль", 
    "deluxe": "делюкс", 
    "royal": "роял", 
    "glade": "глейд", 
    "schauma": "шаума", 
    "zewa": "зева", 
    "aqua": "аква", 
    "junior": "джуниор", 
    "airwick": "эрвик", 
    "air wick": "эрвик", 
    "comfort": "комфорт", 
    "mr. ricco": "мистер рикко", 
    "mr.ricco": "мистер рикко", 
    "mr ricco": "мистер рикко", 
    "ricco": "рикко", 
    "eveline": "эвелин", 
    "oral-b": "орал-би", 
    "oral b": "орал-би", 
    "wella": "велла", 
    "elseve": "эльсев", 
    "greenfield": "гринфилд", 
    "taft": "тафт", 
    "fairy": "фери", 
    "tide": "тайд", 
    "hochland": "хохланд", 
    "ritter": "риттер", 
    "pedigree": "педигри", 
    "knorr": "кнорр", 
    "r o c s": "рокс", 
    "viola": "виола", 
    "ne moloko": "немолоко", 
    "nemoloko": "немолоко", 
    "gallina blanca": "галина бланка", 
    "lay's": "лейс", 
    "lays": "лейс", 
    "oreo": "орео",
    "kinder": "киндер",
    "chocopie": "чокопай",
    "choco-pie": "чокопай",
    "choco pie": "чокопай",
    "meller": "меллер",
    "old": "олд",
    "spice": "спайс",
    "ahmad": "ахмад",
    "kitekat": "китекет",
    "domestos": "доместос",
    "felix": "феликс",
    "maccoffee": "маккофе",
    "vernel": "вернель",
    "barilla": "барилла",
    "chappi": "чаппи",
    "carlsberg": "карлсберг",
}